[versions]
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

coroutines = "1.10.2"
detekt = "1.23.8"
filekit = "0.12.0"
kotlin = "2.2.21"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.12.0"
androidx-core = "androidx.core:core-ktx:1.17.0"

compose-material3-adaptive = "org.jetbrains.compose.material3.adaptive:adaptive:1.2.0"

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }

gifkt = "com.shakster:gifkt-compose:0.3.0"
tiamat = "io.github.composegears:tiamat:2.0.0-rc01"
zoomable = "net.engawapg.lib:zoomable:2.9.0"

detekt-compose = "io.nlopez.compose.rules:detekt:0.5.3"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version = "1.0.0-beta09" }
compose-multiplatform = { id = "org.jetbrains.compose", version = "1.9.3" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }